# Generated by Django 4.2.2 on 2024-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delete', 'delete'), ('approved', 'approved')], default='pending', max_length=200),
        ),
    ]
