# Generated by Django 4.2.2 on 2024-02-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_reviews', to='base.customer'),
        ),
    ]
