# Generated by Django 5.0.2 on 2024-02-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_address_customer_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=True, max_length=200, null=True),
        ),
    ]
