# Generated by Django 5.0.2 on 2024-02-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=True, max_length=200, null=True),
        ),
    ]
