# Generated by Django 5.0.2 on 2024-02-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
