# Generated by Django 5.0.2 on 2024-02-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_product_options_product_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
