# Generated by Django 5.0.2 on 2024-02-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
