# Generated by Django 5.0.2 on 2024-02-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
